name: Update README

on:
  push:
    branches:
      - "master"
    paths:
      - "TIL/learn/**"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          python -m pip install --upgrade pip
          echo "Dependencies installed."
      - name: Update README
        run: |
          echo "Running update_readme.py..."
          python update_readme.py
          echo "update_readme.py completed."
      - name: Commit and push if changed
        run: |
          echo "Configuring git..."
          git config --global user.email "pc5401@naver.com"
          git config --global user.name "pc5401"
          git add README.md
          git commit -m "Update README" || echo "No changes to commit."
          git push
          echo "Changes pushed."
      