name: Update README

on:
  push:
    branches:
      - "master"
      - "main" 
    paths:
      - 'TIL/learn/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TIL  # 작업 디렉토리 설정
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Update README
        run: python update_readme.py
      - name: Commit and push if changed
        run: |
          git config --global user.email "pc5401@naver.com"
          git config --global user.name "pc5401"
          git add README.md
          git commit -m "Update README" || exit 0
          git push
